version: "3.7"
services:
    nginx:
        image: nginx:1.18.0
        volumes:
          - ./nginx/etc:/etc/nginx:cached
          - ../www:/www:cached
        container_name: my-nginx
        ports:
          - "80:80"
        networks:
            backend:
                ipv4_address: 172.19.0.2
    5.6-fpm:
        build:
            context: ./php/5.6
            dockerfile: Dockerfile
        volumes:
          - ./php/5.6/etc:/usr/local/etc:cached
          - ../www:/www:cached
        container_name: my-php56
        expose:
          - "9000"
        networks:
            backend:
                ipv4_address: 172.19.0.3
    db:
        image: mysql:5.6
        ports:
            - 3306:3306
        environment:
            - MYSQL_ROOT_PASSWORD=123456
        volumes:
          - ../dockerMap/mysql/data:/var/lib/mysql:cached
        container_name: my-mysql
        networks:
            backend:
                ipv4_address: 172.19.0.4
    redis:
        image: redis:3.2
        ports:
            - "6379:6379"
        container_name: oms-redis 
        networks:
            backend:
                ipv4_address: 172.19.0.10
networks:
    backend:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 172.19.0.0/16